-- Creating FOREIGN TABLES for Online transactions.

CREATE SCHEMA IF NOT EXISTS offline;

CREATE EXTENSION IF NOT EXISTS file_fdw;

CREATE SERVER IF NOT EXISTS pglog FOREIGN DATA WRAPPER file_fdw;


CREATE FOREIGN TABLE IF NOT EXISTS offline.transactions  (
				Transaction_ID						VARCHAR(255),
				TransactionNo						VARCHAR(255),
				Date_of_tr							VARCHAR(255),
				Product_category_id					VARCHAR(255),
				Product_Category					VARCHAR(255),
				ProductNo							VARCHAR(255),
				ProductName							VARCHAR(255),
				product_desc						VARCHAR(255),
				product_year_of_production			VARCHAR(255),
				product_color						VARCHAR(255),
				Costs								VARCHAR(255),
				Price								VARCHAR(255),
				Quantity							VARCHAR(255),
				CustomerNo							VARCHAR(255),
				customer_name						VARCHAR(255),
				customer_surname					VARCHAR(255),
				customer_birth_date					VARCHAR(255),
				customer_mail						VARCHAR(255),
				customer_gender						VARCHAR(255),
				customer_phone						VARCHAR(255),
				customer_address_id					VARCHAR(255),
				customer_address_apartment			VARCHAR(255),
				customer_home_number				VARCHAR(255),
				customer_postal_code_id				VARCHAR(255),
				customer_postal_code				VARCHAR(255),
				customer_street_id					VARCHAR(255),
				customer_street_name				VARCHAR(255),
				customer_city_id					VARCHAR(255),
				customer_city						VARCHAR(255),
				customer_country_id					VARCHAR(255),
				customer_country_name				VARCHAR(255),
				ShopNo								VARCHAR(255),
				shop_name							VARCHAR(255),
				shop_mail							VARCHAR(255),
				shop_phone							VARCHAR(255),
				shop_address_id						VARCHAR(255),
				shop_address_apartment				VARCHAR(255),
				shop_address_number					VARCHAR(255),
				shop_postal_code_id					VARCHAR(255),
				shop_postal_code					VARCHAR(255),
				shop_street_id						VARCHAR(255),
				shop_street_name					VARCHAR(255),
				shop_city_id						VARCHAR(255),
				shop_city							VARCHAR(255),
				shop_country_id						VARCHAR(255),
				shop_country						VARCHAR(255),
				employee_id							VARCHAR(255),
				employee_first_name					VARCHAR(255),
				employee_last_name					VARCHAR(255),
				employee_email						VARCHAR(255),
				employee_phone						VARCHAR(255),
				employee_gender						VARCHAR(255),
				employee_birth_date					VARCHAR(255),
				employee_address_id					VARCHAR(255),
				employee_address_apartment			VARCHAR(255),
				employee_home_number				VARCHAR(255),
				employee_postal_code_id				VARCHAR(255),
				employee_postal_code				VARCHAR(255),
				employee_street_id					VARCHAR(255),
				employee_street_name				VARCHAR(255),
				employee_city_id					VARCHAR(255),
				employee_city						VARCHAR(255),
				employee_country_id					VARCHAR(255),
				employee_country					VARCHAR(255),
				promotion_id						VARCHAR(255),
				promotion_name						VARCHAR(255),
				channel_id							VARCHAR(255),
				channel_category					VARCHAR(255),
				channel_name						VARCHAR(255)


				) SERVER pglog
			OPTIONS ( filename '/home/kamil/Desktop/Data_set/Offline_ Transactions.csv', format 'csv', HEADER 'TRUE' );
			
		
	CREATE TABLE IF NOT EXISTS offline.src_offline_transactions  (
				Transaction_ID						VARCHAR(255),
				TransactionNo						VARCHAR(255),
				Date_of_tr							VARCHAR(255),
				Product_category_id					VARCHAR(255),
				Product_Category					VARCHAR(255),
				ProductNo							VARCHAR(255),
				ProductName							VARCHAR(255),
				product_desc						VARCHAR(255),
				product_year_of_production			VARCHAR(255),
				product_color						VARCHAR(255),
				Costs								VARCHAR(255),
				Price								VARCHAR(255),
				Quantity							VARCHAR(255),
				CustomerNo							VARCHAR(255),
				customer_name						VARCHAR(255),
				customer_surname					VARCHAR(255),
				customer_birth_date					VARCHAR(255),
				customer_mail						VARCHAR(255),
				customer_gender						VARCHAR(255),
				customer_phone						VARCHAR(255),
				customer_address_id					VARCHAR(255),
				customer_address_apartment			VARCHAR(255),
				customer_home_number				VARCHAR(255),
				customer_postal_code_id				VARCHAR(255),
				customer_postal_code				VARCHAR(255),
				customer_street_id					VARCHAR(255),
				customer_street_name				VARCHAR(255),
				customer_city_id					VARCHAR(255),
				customer_city						VARCHAR(255),
				customer_country_id					VARCHAR(255),
				customer_country_name				VARCHAR(255),
				ShopNo								VARCHAR(255),
				shop_name							VARCHAR(255),
				shop_mail							VARCHAR(255),
				shop_phone							VARCHAR(255),
				shop_address_id						VARCHAR(255),
				shop_address_apartment				VARCHAR(255),
				shop_address_number					VARCHAR(255),
				shop_postal_code_id					VARCHAR(255),
				shop_postal_code					VARCHAR(255),
				shop_street_id						VARCHAR(255),
				shop_street_name					VARCHAR(255),
				shop_city_id						VARCHAR(255),
				shop_city							VARCHAR(255),
				shop_country_id						VARCHAR(255),
				shop_country						VARCHAR(255),
				employee_id							VARCHAR(255),
				employee_first_name					VARCHAR(255),
				employee_last_name					VARCHAR(255),
				employee_email						VARCHAR(255),
				employee_phone						VARCHAR(255),
				employee_gender						VARCHAR(255),
				employee_birth_date					VARCHAR(255),
				employee_address_id					VARCHAR(255),
				employee_address_apartment			VARCHAR(255),
				employee_home_number				VARCHAR(255),
				employee_postal_code_id				VARCHAR(255),
				employee_postal_code				VARCHAR(255),
				employee_street_id					VARCHAR(255),
				employee_street_name				VARCHAR(255),
				employee_city_id					VARCHAR(255),
				employee_city						VARCHAR(255),
				employee_country_id					VARCHAR(255),
				employee_country					VARCHAR(255),
				promotion_id						VARCHAR(255),
				promotion_name						VARCHAR(255),
				channel_id							VARCHAR(255),
				channel_category					VARCHAR(255),
				channel_name						VARCHAR(255),
				insert_dt							DATE DEFAULT CURRENT_DATE
			);
		
INSERT INTO offline.src_offline_transactions

SELECT 			Transaction_ID,
				TransactionNo,
				Date_of_tr,
				Product_category_id,
				Product_Category,
				ProductNo,
				ProductName,
				product_desc,
				product_year_of_production,
				product_color,
				Costs,
				Price,
				Quantity,
				CustomerNo,
				customer_name,
				customer_surname,
				customer_birth_date,
				customer_mail,
				customer_gender,
				customer_phone,
				customer_address_id,
				customer_address_apartment,
				customer_home_number,
				customer_postal_code_id,
				customer_postal_code,
				customer_street_id,
				customer_street_name,
				customer_city_id,
				customer_city,
				customer_country_id,
				customer_country_name,
				ShopNo,
				shop_name,
				shop_mail,
				shop_phone,
				shop_address_id,
				shop_address_apartment,
				shop_address_number,
				shop_postal_code_id,
				shop_postal_code,
				shop_street_id,
				shop_street_name,
				shop_city_id,
				shop_city,
				shop_country_id,
				shop_country,
				employee_id,
				employee_first_name,
				employee_last_name,
				employee_email,
				employee_phone,
				employee_gender,
				employee_birth_date,
				employee_address_id,
				employee_address_apartment,
				employee_home_number,
				employee_postal_code_id,
				employee_postal_code,
				employee_street_id,
				employee_street_name,
				employee_city_id,
				employee_city,
				employee_country_id,
				employee_country,
				promotion_id,
				promotion_name,
				channel_id,
				channel_category,
				channel_name
FROM offline.transactions;

SELECT * FROM offline.src_offline_transactions


