CREATE TABLE IF NOT EXISTS bl_dm.DIM_EMPLOYEES (
					employees_surr_id		BIGINT NOT NULL UNIQUE,
					employees_src_id		VARCHAR(255) NOT NULL,
					source_system			VARCHAR(255) NOT NULL,
					source_entity			VARCHAR(255) NOT NULL,
					employee_address_id		VARCHAR(255) NOT NULL,
					employee_name			VARCHAR(255) NOT NULL,
					employee_surname		VARCHAR(255) NOT NULL,
					employee_phone			VARCHAR(255) NOT NULL,
					employee_email			VARCHAR(255) NOT NULL,
					employee_country_id		VARCHAR(255) NOT NULL,
					employee_country_name	VARCHAR(255) NOT NULL,
					employee_city_id		VARCHAR(255) NOT NULL,
					employee_city_name		VARCHAR(255) NOT NULL,
					employee_postal_code_id	VARCHAR(255) NOT NULL,
					employee_postal_code	VARCHAR(255) NOT NULL,
					employee_street_id		VARCHAR(255) NOT NULL,
					employee_street_name	VARCHAR(255) NOT NULL,
					employee_apartment		VARCHAR(255) NOT NULL,
					employee_address_number	VARCHAR(255) NOT NULL,
					update_dt				DATE NOT NULL,
					insert_dt				DATE NOT NULL
);