INSERT INTO bl_dm.dim_customers
	(customers_surr_id,
	customers_src_id,
	source_system,
	source_entity,
	customer_name,
	customer_surname,
	customer_phone,
	customer_email,
	customer_country_id,
	customer_country_name,
	customer_city_id,
	customer_city_name,
	customer_postal_code_id,
	customer_postal_code,
	customer_street_id,
	customer_street_name,
	customer_address_id,
	customer_apartment,
	customer_address_number,
	update_dt,
	insert_dt)
VALUES(-1,
		'-1',
		'n/A',
		'N/A',
		'N/A',
		'N/A',
		'N/A',
		'N/A', 
		'-1', 
		'N/A',
		'-1', 
		'N/A', 
		'-1', 
		'N/A', 
		'-1', 
		'N/A', 
		'-1',
		'N/A',
		'N/A', 
		'18000101'::DATE,
		'99990101'::DATE)

ON CONFLICT DO NOTHING;

COMMIT;
